import HTMLHead from 'next/head'

const title = "Anthony Mittz"
const description = "Generated by create next app";

export default function Head() {
  return <HTMLHead>
    <title>{title}</title>
    <meta name="description" content={description} />
    <link rel="icon" href="/favicon/favicon.ico" />
  </HTMLHead>
}